### PR TITLE
Just update docker stuff

### PR DESCRIPTION
**Pull request by snazy**

### CODE REVIEW

**Comment by omarsmak** [comment]
I think this shouldn't be happening, the last commit to the docker folder is this [one](https://github.com/projectnessie/nessie-demos/commit/35c9e3b45d789bd935afda806e124794a415a49b#diff-d548c5b83fa61d8e3bd86ad42a7ffea9b7c86e3f9d8095c1577d3e1270bb9420). I am not sure why it's happing 🤔

**Comment by snazy** [comment]
> I think this shouldn't be happening, the last commit to the docker folder is this [one](https://github.com/projectnessie/nessie-demos/commit/35c9e3b45d789bd935afda806e124794a415a49b#diff-d548c5b83fa61d8e3bd86ad42a7ffea9b7c86e3f9d8095c1577d3e1270bb9420). I am not sure why it's happing 🤔

But we need to fix it, it’s in the pre-commit stuff

**Comment by omarsmak** [comment]
> > I think this shouldn't be happening, the last commit to the docker folder is this [one](https://github.com/projectnessie/nessie-demos/commit/35c9e3b45d789bd935afda806e124794a415a49b#diff-d548c5b83fa61d8e3bd86ad42a7ffea9b7c86e3f9d8095c1577d3e1270bb9420). I am not sure why it's happing 🤔
> 
> But we need to fix it, it’s in the pre-commit stuff

Yeah of course, I started looking at it, still didn't figure out the root cause for it 'yet', I thought it maybe the cause with different python version since checksumdir is using hashlib but that didn't have an effect. I will investigate further why is happening

**Comment by omarsmak** [comment]
@snazy this seems to be from my end, after I have cleaned the folder, got the same sha1 as yours, sorry my bad 😅 . 

I have also added a args to prevent hidden files .. etc here: https://github.com/projectnessie/nessie-demos/pull/232. Once that is is merged, we can merge this one so the CI can kick in.

**Comment by snazy** [comment]
THink we should merge this one and your PR then ;)

**Comment by omarsmak** [comment]
> THink we should merge this one and your PR then ;)

Ah true, will update my PR then 😅

**Comment by omarsmak** [comment]
Added in https://github.com/projectnessie/nessie-demos/pull/232/files

**Pull request closed without merging**
